#!/bin/bash

filename=$1
if [[ -d "$filename" ]]; then
    # we have a directory and lets set the volume mount here
    dir=$(readlink -e "$filename")
    file="/data"

elif [[ -f "$filename" ]]; then
    # this is a regular file so lets make the volume the directory
    # the file lives in and mount that
    abs=$(readlink -f "$filename")
    dir=$(dirname "$abs")
    file=$(basename "$abs")
fi
docker run -it --rm -v "$dir":/data fxdgear/alpine-neovim:latest /usr/local/bin/nvim "$file"
